# Generated by Django 4.0.1 on 2022-01-29 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatroom_room_id_alter_messages_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='room_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='chat.chatroom'),
        ),
    ]
