# Generated by Django 4.0.1 on 2022-01-21 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.SmallIntegerField(validators=[django.core.validators.MinLengthValidator(15)]),
        ),
    ]
