# Generated by Django 4.0.1 on 2022-01-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='product_path',
            field=models.ImageField(upload_to='media'),
        ),
    ]
