# Generated by Django 4.0.1 on 2022-01-22 07:17

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productdetails_product_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='product_path',
            field=models.ImageField(upload_to=django.core.files.storage.FileSystemStorage(location='/assets/images')),
        ),
    ]
