# Generated by Django 4.0.1 on 2022-01-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productdetails_product_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='product_path',
            field=models.CharField(max_length=100),
        ),
    ]
