# Generated by Django 4.0.1 on 2022-01-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productdetails_product_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttags',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='producttags',
            name='tag',
            field=models.CharField(choices=[('MB', 'Motivational Books'), ('DB', 'Defence Books'), ('CB', 'College Level Books'), ('NO', 'Novels')], max_length=2),
        ),
    ]
